#!/bin/bash
set -e

if [ ! $(command -v java) ]; then
    apt-get update
    apt-get install -y --no-install-recommends default-jre
fi

if [ ! $(command -v tox) ]; then
    apt-get update
    apt-get install -y --no-install-recommends tox python3-virtualenv
fi

if [ ! $(command -v zip) ]; then
    apt-get update
    apt-get install -y --no-install-recommends zip xz-utils
fi

if [ ! $(command -v rsync) ]; then
    apt-get update
    apt-get install -y --no-install-recommends rsync
fi
