#!/bin/bash
set -e

SCRATCH_TEMP=

trap destroy_root exit

setup_root()
{
    if [ -d /scratch ]; then
        SCRATCH_TEMP=$(mktemp -d /scratch/cattle.XXXXX)
        rsync --exclude '*.pyc' -a ./ $SCRATCH_TEMP
        pushd $SCRATCH_TEMP
    fi
}

destroy_root()
{
    if [[ -n "$SCRATCH_TEMP" && -d "$SCRATCH_TEMP" ]]; then
        popd
        rsync --delete -a ${SCRATCH_TEMP}/tests/integration/.tox ./tests/integration
        rm -rf "$SCRATCH_TEMP"
    fi
}

cd $(dirname $0)/..

go test -race -cover -tags=test ./...

setup_root

cd tests/integration
export CATTLE_URL=${CATTLE_URL:-http://localhost:8080/v2-beta/schemas}

if [ "${SKIP_INTEGRATION:-false}" = "true" ]; then
    echo "Skipping Python integration tests because SKIP_INTEGRATION=true"
else
    tox "$@"
fi

echo OK
