#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

echo Running: go vet
go vet ./...
echo Running: go fmt
test -z "$(gofmt -l -s -- $(find . -path './vendor' -prune -o -name '*.go' -type f -print) | tee /dev/stderr)"
