#!/bin/bash

if [ -n "${VERSION_OVERRIDE:-}" ]; then
    VERSION="$VERSION_OVERRIDE"
    return 0 2>/dev/null || exit 0
fi


DIRTY=
if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
TAG=$(git tag -l --contains HEAD | head -n 1)

if [[ -z "$DIRTY" && -n "$TAG" ]]; then
    VERSION=$TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi
